# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publish-api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install redoc-cli
          npm install -g redoc-cli
      - name: Build and publish API documentation
        env:
          REDOCLY_API_KEY: ${{ secrets.TEST_API_KEY }}
          REPO_NAME: "shereengrg/RedoclyTestActions"
        run: |
          redoc-cli bundle openapi.yaml -o index.html --template redoc --options.hideDownloadButton=true
          curl -H "Content-Type: text/html" -H "Authorization: ApiKey $TEST_API_KEY" -X PUT https://api.redoc.ly/v2/streams/github/$REPO_NAME/versions/latest/content -d @index.html
